[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://myrecipefinder-prod.up.railway.app/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
