[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://myrecipefinder-backend.onrender.com/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
