# Railway configuration for React frontend
[build]
builder = "nixpacks"

[build.env]
NODE_ENV = "production"

[deploy]
healthcheckPath = "/"
# Removed: startCommand = "npm run preview"

[services.frontend]
type = "web"
name = "myrecipefinder-frontend"
runtime = "nodejs"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT"

[services.frontend.envVars]
VITE_API_BASE_URL = "https://myrecipefinder-prod.up.railway.app"
NODE_ENV = "production"
