# Vercel + Railway Backend Option
# Use this instead of render.yaml if you prefer Railway

[[services]]
type = "web"
name = "myrecipefinder-backend"
runtime = "python3"
buildCommand = "cd backend && python3 -m pip install -r requirements.txt"
startCommand = "./start.sh"

[services.envVars]
FLASK_ENV = "production"
COHERE_API_KEY = "@COHERE_API_KEY"
TAVILY_API_KEY = "@TAVILY_API_KEY"
DATABASE_URL = "@DATABASE_URL"
