# Railway Python deployment
# Railway should auto-detect Python and install from requirements.txt

[[services]]
type = "web"
name = "myrecipefinder-backend"
runtime = "python3"
startCommand = "python3 main.py"

[services.envVars]
FLASK_ENV = "production"
FRONTEND_ORIGIN = "https://myrecipefinder.up.railway.app,https://myrecipefinder-frontend-production.up.railway.app,https://myrecipefinder-prod.up.railway.app"
COHERE_API_KEY = "@COHERE_API_KEY"
TAVILY_API_KEY = "@TAVILY_API_KEY"
DATABASE_URL = "@DATABASE_URL"
LLM_MODEL = "command-a-03-2025"
FATSECRET_APP_KEY = "@FATSECRET_APP_KEY"
FATSECRET_APP_SECRET = "@FATSECRET_APP_SECRET"
SPOONACULAR_API_KEY = "@SPOONACULAR_API_KEY"
