# Railway configuration for React frontend
[build]
builder = "nixpacks"

[build.env]
NODE_ENV = "production"

[deploy]
healthcheckPath = "/"

[services.frontend]
type = "web"
name = "myrecipefinder-frontend"
runtime = "nodejs"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npx serve dist -s -p $PORT"

[services.frontend.envVars]
NODE_ENV = "production"
