# Simplified Railway configuration
# Railway should auto-detect Python app

[[services]]
type = "web"
name = "myrecipefinder-backend"
runtime = "python3"
startCommand = "python3 main.py"

[services.envVars]
FLASK_ENV = "production"
COHERE_API_KEY = "@COHERE_API_KEY"
TAVILY_API_KEY = "@TAVILY_API_KEY"
DATABASE_URL = "@DATABASE_URL"
