# Vercel + Railway Backend Option
# Use this instead of render.yaml if you prefer Railway

[[services]]
type = "web"
name = "myrecipefinder-backend"
runtime = "python3"
buildCommand = "cd backend && pip install -r requirements.txt"
startCommand = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"

[services.envVars]
FLASK_ENV = "production"
COHERE_API_KEY = "@COHERE_API_KEY"
TAVILY_API_KEY = "@TAVILY_API_KEY"
DATABASE_URL = "@DATABASE_URL"
